name: weather_zheer
description: "A cross-platform Flutter weather application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  intl: ^0.20.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  url_launcher: ^6.3.0
  translator: ^1.0.4+1
  fl_chart: ^0.68.0
  device_preview: ^3.0.0-prerelease3
  flutter_tts: ^4.2.5
  webview_flutter: ^4.10.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21